todo_app/core/models.py
from todo_app.extensions import db

class Todo(db.Model):
    id = db.Column(db.Integer, primary_key=True)
    title = db.Column(db.String(50), nullable=False, unique=True)
    is_done = db.Column(db.Integer, default=0)

    def __repr__(self) -> str:
        return f'<Todo: {self.title}>'
    
    def __str__(self) -> str:
        return f'<Todo: {self.title}>'

todo_app/core/routes.py
from flask import Blueprint, render_template, request, abort
from flask.wrappers import Response
from todo_app.core.models import Todo
from sqlalchemy.exc import IntegrityError

from todo_app.extensions import db

core = Blueprint(
    'core',
    __name__,
    url_prefix='/todos',
    template_folder='templates',
    static_folder='static',
    static_url_path='/static/core',
)


@core.route('/', methods=['GET', 'POST'])
def index():
    todos = Todo.query.all()
    context = {
        'todos': todos,
    }
    return render_template('core/index.html', **context)

@core.route('/todo/create', methods=['POST'])
def add_todo():
    if request.method == 'POST':
        title = str(request.form['todo_title']).strip()
        if not title: abort(400)
        todo = Todo(title=title)
        try:
            db.session.add(todo)
            db.session.commit()
        except IntegrityError as e:
            db.session.rollback()
            abort(400)
        else:
            return render_template('core/todo.html', todo=todo)

@core.route('/todo/<id>/update', methods=['PUT'])
def update_todo(id):
    if request.method == 'PUT':
        todo = Todo.query.get(id)
        todo.is_done = 1
        try:
            db.session.commit()
            return render_template('core/todo.html', todo=todo)
        except Exception as e:
            db.session.rollback()
            abort(400)


@core.route('/todo/<id>/delete', methods=['DELETE'])
def delete_todo(id):
    if request.method == 'DELETE':
        todo = Todo.query.get(id)
        try:
            db.session.delete(todo)
            db.session.commit()
            return Response(status=200) 
        except Exception as e:
            db.session.rollback()
            abort(400)

todo_app/core/templates/core/base.html
<!DOCTYPE html>
<html lang="en">
  <head>
    <title>TODO Flask App</title>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <link href="css/style.css" rel="stylesheet">
    <link rel="stylesheet" href="{{ url_for('static', filename='css/style.css') }}">
  </head>
  <body class="bg-emerald-400">

  {% block content %}
  <!-- Content -->
  {% endblock content %}

  <script src="{{url_for('static', filename='js/htmx.min.js')}}"></script>
  </body>
</html>

todo_app/core/templates/core/index.html
{% extends 'core/base.html' %}

{% block content %}
<div class="flex items-center py-6 bg-emerald-300">
    <h1 class="text-4xl text-slate-900">TODO APP</h1>
  </div>
  
  <div class="w-4/5 my-6 mx-auto p-2 lg:p-10  rounded-xl bg-white">
    <form 
        class="flex mb-6 space-x-4"
        hx-post="{{ url_for('core.add_todo') }}"
        hx-target="#todos"
        hx-swap="beforeend"
    >
      <input id="'todo_title" name ="todo_title" type="text" class="title flex-1 px-4 py-3 bg-gray-200 rounded-xl" placeholder="Todo Title">
      <button class="p-3 rounded-xl text-white bg-emerald-600 hover:bg-emerald-500" >Submit</button>
    </form>

    {% include 'core/todo_table.html' %}


  </div>
{% endblock content %}

todo_app/core/templates/core/todo.html
<tr class="flex-1 {% if todo.is_done %} bg-cyan-100 {% endif %}" id="todo_{{todo.id}}">
  <form hx-put="{{ url_for('core.update_todo', id=todo.id) }}"
    hx-target="#todo_{{todo.id}}" hx-swap="outerHTML">
    <td class="w-4/5 py-3">
      <div>
        <p class="px-6 text-xs text-gray-900">{{ todo.title }}</p>
      </div>
    </td>
    <td class="w-1/5 py-3">
      <div class="px-6 flex justify-end space-x-4 text-right">
        {% if not todo.is_done %}
        <button class="text-emerald-600 hover:text-emerald-500">Done</button>
        {% endif %}
        <a class="text-emerald-600 hover:text-emerald-500" hx-target="closest tr" hx-swap="outerHTML swap:1s"
          hx-delete="{{ url_for('core.delete_todo', id=todo.id) }}">
          Delete
        </a>
      </div>
    </td>
  </form>
</tr>

todo_app/core/templates/core/todo_table.html
<table class="flex-1 py-3 rounded-xl bg-gray-100 w-full">
  <thead class="">
    <tr>
      <th class="w-4/5 px-6 text-sx font-medium text-gray-500 uppercase text-left">Title</th>
      <th class="w-1/5 text-xs font-medium text-gray-500 uppercase">Actions</th>
    </tr>
  </thead>
  <tbody class="divide-y divide-gray-200" id="todos">
    {% for todo in todos %}
    
    {% include 'core/todo.html' %}

    {% endfor %}
  </tbody>
</table>